CREATE TABLE IF NOT EXISTS CARGO.CARGO_REPORT
(
    ID SERIAL PRIMARY KEY,
    CARGO_JSON VARCHAR,
    CARGO VARCHAR,
    TRUCK VARCHAR(100),
    PARCELS VARCHAR,
    TRUCK_COUNT INTEGER,
    ALGORITHM VARCHAR(100),
    CREATED_DATE TIMESTAMP NOT NULL
)